services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist

  - type: web
    name: admin
    env: static
    plan: free
    buildCommand: cd admin && npm install && npm run build
    staticPublishPath: admin/dist

